# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a88e0acb8b7f8331ba25369318aaab307fc38332653fc8f12847806ee843bb718c39642fe5e5dd80ee3917424048cb674daf59bc2854c250925e0daedc8b103

test:
  secret_key_base: 0a934fd96f8730974a307da744bfcff216b679619c1b661f6d1884f4d17140147bf6905fb65ab91fa1e4e62ee6fd0a0f46261480583f53c60fed6cf23e6fb938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
